### ISSUE TITLE
Concept/Design

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-welcome-wizard#1]
Idea
====

The idea of the welcome wizard is to  basically introduce the major features of the desktop to the user. It also attracts and helps the user to know about the OS. It is also called a _welcome screen_ and is used to guide the user on how to use the system just after installation. It is used in almost all popular distributions these days.

Design
====
- ![#26c6da](https://placehold.it/15/26c6da/000000?text=+) `#26c6da` 50% Opacity
- ![#5c6bc0](https://placehold.it/15/5c6bc0/000000?text=+) `#5c6bc0`
![](https://i.imgur.com/mJ45oOb.png)

- ![#42a5f5](https://placehold.it/15/42a5f5/000000?text=+) `#42a5f5` 50% Opacity
- ![#0277bd](https://placehold.it/15/0277bd/000000?text=+) `#0277bd`
![](https://i.imgur.com/FKfIkXK.png)

- ![#03a9f4](https://placehold.it/15/03a9f4/000000?text=+) `#03a9f4` 50% Opacity
- ![#607d8b](https://placehold.it/15/607d8b/000000?text=+) `#607d8b`
![](https://i.imgur.com/KH4M5br.png)

- ![#ff9800](https://placehold.it/15/ff9800/000000?text=+) `#ff9800` 50% Opacity
- ![#5d4037](https://placehold.it/15/5d4037/000000?text=+) `#5d4037`
![](https://i.imgur.com/0FkpFYl.png)

- ![#e91e63](https://placehold.it/15/e91e63/000000?text=+) `#e91e63` 50% Opacity
- ![#673ab7](https://placehold.it/15/673ab7/000000?text=+) `#673ab7`
![](https://i.imgur.com/orhlxXk.png)

- ![#26c6da](https://placehold.it/15/26c6da/000000?text=+) `#26c6da`
- ![#fafafa](https://placehold.it/15/fafafa/000000?text=+) `#fafafa`
- ![#f5f5f5](https://placehold.it/15/f5f5f5/000000?text=+) `#f5f5f5`
- ![#eeeeee](https://placehold.it/15/eeeeee/000000?text=+) `#eeeeee`
![](https://i.imgur.com/v9ZDiqB.png)

**Comment by anupam-git** [comment]
Will be needing the background images. Please push the background Images in this repo.
