### ISSUE TITLE
Add checkbox to disable welcome wizard

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nx-welcome-wizard#3]
By default the program starts automatically, this is ok for the first time, but there's no way to disable this other than deleting `/etc/xdg/autostart/nx-welcome-wizard.desktop.`

The Welcome Wizard should have a checkbox that disables (deletes that file) the program from autostarting.

**Comment by lslvr** [comment]
Isn't it possible to add that file to the user's home directory instead, which is writeable?

**Comment by UriHerrera** [comment]
`/etc/xdg/autostart` is the standard path to put autostarting programs.

Latte is also added to that path and it's available to be disabled from autostarting in System Settings but not Welcome Wizard.

Maybe the desktop launcher is missing something?.

**Comment by lslvr** [comment]
What about `~/.config/autostart`? That path could work if we include it in `/etc/skel`.

**Comment by UriHerrera** [comment]
Let me update the package to test.

**Comment by lslvr** [comment]
Sure!

**Comment by UriHerrera** [comment]
It can now be disabled from auto-starting in System Settings.

![VirtualBox_Nitrux_25_09_2019_13_28_13](https://user-images.githubusercontent.com/3053525/65629086-612ef080-df98-11e9-9927-d8b7097e2d40.png)

**Comment by lslvr** [comment]
@UriHerrera, would it be possible to add a button in the application screen (as a shortcut)? That way, you don't need to go to system settings to disable it. :smile:

**Comment by UriHerrera** [comment]
It does show a shortcut to open System Settings, and auto-starting a program is a setting of the system.

![image](https://user-images.githubusercontent.com/3053525/65638107-0652c480-dfab-11e9-9646-5893be23a6e8.png)

**Comment by lslvr** [comment]
I found it. But I meant a button that removes the autostart option from within the app itself (removing the need of opening another application for such a trivial action). Is it possible to do so (to disable the setting) from within nx-welcome-wizard?

**Comment by UriHerrera** [comment]
Yes, it just needs a button that deletes `/etc/skel/.config/autostart/nx-welcome-wizard.desktop`

**Comment by luis-lavaire** [comment]
Yep. That's what I mean. Can it be done from the same GUI?

**Comment by anupam-git** [comment]
I suppose the path is meant to be `~/.config/autostart/nx-welcome-wizard.desktop` instead.

**Comment by lslvr** [comment]
Indeed, @anupam-git!

**Comment by anupam-git** [comment]
Working on it..

**Comment by anupam-git** [comment]
@UriHerrera Can you please test the `development` branch??

**Comment by lslvr** [comment]
@anupam-git @UriHerrera, what's the status of this, guys?

**Comment by UriHerrera** [comment]
It hasn't been added yet to the `master` branch.

**Comment by anupam-git** [comment]
Does it require any more updates??

**Comment by UriHerrera** [comment]
![VirtualBox_Nitrux_26_06_2020_01_29_19](https://user-images.githubusercontent.com/3053525/85827802-9e552880-b74c-11ea-9285-59e0e58cb8b0.png)

It's added but it's not styled.

**Comment by UriHerrera** [comment]
![image](https://user-images.githubusercontent.com/3053525/86115280-5a865a00-ba91-11ea-8b87-3c6d8876b4ce.png)

It's styled now https://github.com/Nitrux/nx-welcome-wizard/commit/5f2c195bae7d9bd1a08017b70120b2d1fef25bc2.
